insert into ProductDescription (PrductDescriptionID, Description) values (3,"Choromoly steel")
insert into ProductDescription (PrductDescriptionID, Description) values (4,"Aluminium alloy cups; large diameter spindle.")
insert into ProductDescription (PrductDescriptionID, Description) values (5,"Aluminium alloy cups and a hollow axle")
insert into ProductDescription (PrductDescriptionID, Description) values (8,"Suitable for any type of riding, on or off-road. Fits any budget. Smooth-Shifting with a confortable ride")
insert into ProductDescription (PrductDescriptionID, Description) values (64,"This bike delivers a high-level of performance on a budget. It is responsive and maneuverable, and offers peace-of-mind whe yo decide to go off-road")